name: Pipeline

on: [push]

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

  tests:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        mongodb-version: [ '4.2', '4.4', '5.0', '6.0' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-port: 27017
          mongodb-version: '6.0'

      - name: Unit and intgr tests
        run: go test -v -count=1 -race -timeout=1m ./...
